name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

# permissions:
# contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Get pnpm cache directory
        id: pnpm-cache-dir
        shell: bash
        run: echo "dir=$(pnpm config get store-dir)" >> ${GITHUB_OUTPUT}
      - name: Install and Build 🔧
        run: |
          pnpm install
          pnpm build

      # - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      #   run: |
      #     npm i
      #     npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
